-- V1: Initial schema baseline.
--
-- The schema was previously produced by Hibernate's `ddl-auto: update`. This
-- migration freezes it in a reviewable, ordered file so it no longer depends on
-- the database's prior state. Everything here is portable between the
-- PostgreSQL production database and the H2 (PostgreSQL mode) dev/test
-- databases: identity primary keys, NUMERIC for money and coordinates, BOOLEAN
-- for flags, VARCHAR(255) for enum-backed columns (Hibernate's STRING mapping).

CREATE TABLE farms (
    farm_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_name   VARCHAR(255) NOT NULL,
    location    VARCHAR(255),
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP
);

CREATE TABLE users (
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    phone         VARCHAR(255),
    farm_name     VARCHAR(255),
    location      VARCHAR(255),
    timezone      VARCHAR(255),
    language      VARCHAR(255),
    created_at    TIMESTAMP,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE user_farms (
    user_id BIGINT NOT NULL,
    farm_id BIGINT NOT NULL,
    CONSTRAINT pk_user_farms PRIMARY KEY (user_id, farm_id),
    CONSTRAINT fk_user_farms_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_user_farms_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id)
);

CREATE TABLE cows (
    cow_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id       BIGINT NOT NULL,
    tag_id        VARCHAR(255) NOT NULL,
    name          VARCHAR(255) NOT NULL,
    date_of_birth DATE,
    breed         VARCHAR(255),
    mother_id     BIGINT,
    father_id     BIGINT,
    caretaker_id  BIGINT,
    created_at    TIMESTAMP,
    CONSTRAINT uk_cows_tag_id UNIQUE (tag_id),
    CONSTRAINT fk_cows_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_cows_mother FOREIGN KEY (mother_id) REFERENCES cows (cow_id),
    CONSTRAINT fk_cows_father FOREIGN KEY (father_id) REFERENCES cows (cow_id),
    CONSTRAINT fk_cows_caretaker FOREIGN KEY (caretaker_id) REFERENCES users (user_id)
);

CREATE TABLE alerts (
    alert_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id     BIGINT NOT NULL,
    cow_id      BIGINT NOT NULL,
    alert_type  VARCHAR(255) NOT NULL,
    message     VARCHAR(255),
    is_resolved BOOLEAN,
    created_at  TIMESTAMP,
    CONSTRAINT fk_alerts_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_alerts_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE vaccinations (
    vaccination_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id           BIGINT NOT NULL,
    cow_id            BIGINT NOT NULL,
    vaccine_name      VARCHAR(255) NOT NULL,
    administered_date DATE,
    next_due_date     DATE,
    vet_name          VARCHAR(255),
    notes             VARCHAR(255),
    created_at        TIMESTAMP,
    CONSTRAINT fk_vaccinations_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_vaccinations_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE health_metrics (
    metric_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id       BIGINT NOT NULL,
    cow_id        BIGINT NOT NULL,
    temperature   NUMERIC(4, 1),
    heart_rate    NUMERIC(5, 1),
    activity_level NUMERIC(5, 1),
    recorded_at   TIMESTAMP NOT NULL,
    CONSTRAINT fk_health_metrics_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_health_metrics_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE location_records (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id     BIGINT NOT NULL,
    cow_id      BIGINT NOT NULL,
    latitude    NUMERIC(9, 6) NOT NULL,
    longitude   NUMERIC(9, 6) NOT NULL,
    accuracy    NUMERIC(5, 2),
    recorded_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_location_records_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_location_records_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE geofences (
    geofence_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id         BIGINT NOT NULL,
    cow_id          BIGINT NOT NULL,
    center_latitude NUMERIC(9, 6) NOT NULL,
    center_longitude NUMERIC(9, 6) NOT NULL,
    radius_meters   INTEGER NOT NULL,
    created_at      TIMESTAMP,
    CONSTRAINT uk_geofences_cow_id UNIQUE (cow_id),
    CONSTRAINT fk_geofences_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_geofences_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE reminders (
    reminder_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id       BIGINT NOT NULL,
    cow_id        BIGINT NOT NULL,
    reminder_type VARCHAR(255) NOT NULL,
    frequency     VARCHAR(255) NOT NULL,
    start_date    DATE NOT NULL,
    is_completed  BOOLEAN,
    created_at    TIMESTAMP,
    CONSTRAINT fk_reminders_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_reminders_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE health_records (
    health_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id     BIGINT NOT NULL,
    cow_id      BIGINT NOT NULL,
    diagnosis   VARCHAR(255) NOT NULL,
    treatment   VARCHAR(255),
    vet_name    VARCHAR(255),
    record_date DATE NOT NULL,
    created_at  TIMESTAMP,
    CONSTRAINT fk_health_records_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_health_records_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE production_records (
    production_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id       BIGINT NOT NULL,
    cow_id        BIGINT NOT NULL,
    record_date   DATE NOT NULL,
    milk_litres   NUMERIC(8, 2),
    weight_kg     NUMERIC(8, 2),
    created_at    TIMESTAMP,
    CONSTRAINT uk_production_records_cow_date UNIQUE (cow_id, record_date),
    CONSTRAINT fk_production_records_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_production_records_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE financial_records (
    financial_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farm_id      BIGINT NOT NULL,
    user_id      BIGINT NOT NULL,
    cow_id       BIGINT,
    entry_type   VARCHAR(255) NOT NULL,
    amount       NUMERIC(12, 2) NOT NULL,
    category     VARCHAR(255),
    description  VARCHAR(255),
    record_date  DATE NOT NULL,
    created_at   TIMESTAMP,
    CONSTRAINT fk_financial_records_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_financial_records_user FOREIGN KEY (user_id) REFERENCES users (user_id),
    CONSTRAINT fk_financial_records_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

CREATE TABLE user_preferences (
    preferences_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL,
    theme              VARCHAR(255),
    language           VARCHAR(255),
    timezone           VARCHAR(255),
    units              VARCHAR(255),
    email_notifications BOOLEAN,
    push_notifications BOOLEAN,
    alert_notifications BOOLEAN,
    weekly_reports     BOOLEAN,
    updated_at         TIMESTAMP,
    CONSTRAINT uk_user_preferences_user_id UNIQUE (user_id),
    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id) REFERENCES users (user_id)
);