-- V2: Tracking devices, and indexes for the paths ingestion hammers.
--
-- Devices are the source of every position and vital sign. Until now those had
-- to be POSTed by hand through the authenticated user API, which meant a human
-- was the sensor.

CREATE TABLE devices (
    device_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number    VARCHAR(255) NOT NULL,
    farm_id          BIGINT NOT NULL,
    -- Null while a collar is provisioned but not yet fitted to an animal.
    cow_id           BIGINT,
    api_key_hash     VARCHAR(255) NOT NULL,
    status           VARCHAR(255) NOT NULL,
    battery_percent  INTEGER,
    firmware_version VARCHAR(255),
    last_seen_at     TIMESTAMP,
    created_at       TIMESTAMP,
    CONSTRAINT uk_devices_serial UNIQUE (serial_number),
    CONSTRAINT fk_devices_farm FOREIGN KEY (farm_id) REFERENCES farms (farm_id),
    CONSTRAINT fk_devices_cow FOREIGN KEY (cow_id) REFERENCES cows (cow_id)
);

-- Every ingested reading is checked against existing rows for the same animal
-- and timestamp, because a collar that does not get an acknowledgement will
-- resend the batch. Without these that check is a table scan per reading.
CREATE INDEX idx_location_records_cow_recorded ON location_records (cow_id, recorded_at);
CREATE INDEX idx_health_metrics_cow_recorded ON health_metrics (cow_id, recorded_at);

-- The live map and the collar sweep both ask for the newest row per animal
-- within a farm.
CREATE INDEX idx_location_records_farm_cow ON location_records (farm_id, cow_id, recorded_at);

-- The sweep and the alert feed both filter on unresolved alerts per farm.
CREATE INDEX idx_alerts_farm_unresolved ON alerts (farm_id, is_resolved);

-- Devices authenticate by serial on every batch.
CREATE INDEX idx_devices_farm ON devices (farm_id);
